/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "forest": "#114232",
        "forest-hover": "#16533F",
        "chlorophyll": "#16A34A",
        "water": "#0284C7",
        "canvas": "#F9FAF6",
        "caution": "#D97706",
        "critical": "#DC2626",
        "hairline": "#E2E8DE",
        "field": "#D1D9CD",
        "sage": "#F1F5EE",
        "surface-dim": "#d9dad7",
        "secondary-fixed": "#7ffc97",
        "secondary-fixed-dim": "#62df7d",
        "inverse-on-surface": "#f0f1ed",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#204f3e",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "primary-fixed": "#bbedd6",
        "on-secondary-container": "#007230",
        "on-primary-container": "#7eae99",
        "error": "#ba1a1a",
        "inverse-surface": "#2e312f",
        "on-secondary-fixed": "#002109",
        "on-primary": "#ffffff",
        "background": "#f9faf6",
        "surface-container": "#edeeea",
        "tertiary-container": "#003e61",
        "tertiary-fixed": "#cce5ff",
        "primary": "#002b1e",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#005320",
        "on-tertiary-container": "#4cacf1",
        "surface-container-low": "#f3f4f0",
        "on-tertiary-fixed": "#001d31",
        "surface": "#f9faf6",
        "on-tertiary-fixed-variant": "#004b73",
        "surface-tint": "#396755",
        "on-primary-fixed": "#002116",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#93ccff",
        "outline-variant": "#c0c8c3",
        "on-background": "#191c1a",
        "secondary-container": "#7cf994",
        "inverse-primary": "#a0d1bb",
        "on-surface": "#191c1a",
        "surface-bright": "#f9faf6",
        "primary-container": "#114232",
        "outline": "#717974",
        "surface-variant": "#e2e3df",
        "surface-container-high": "#e7e9e5",
        "surface-container-highest": "#e2e3df",
        "primary-fixed-dim": "#a0d1bb",
        "secondary": "#006e2d",
        "on-surface-variant": "#414944",
        "tertiary": "#002740",
        "on-tertiary": "#ffffff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "space-lg": "1.5rem",
        "gutter": "1.5rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "margin": "2rem",
        "gutter-mobile": "0.75rem",
        "space-md": "1rem",
        "margin-mobile": "1rem",
        "space-xl": "2.5rem"
      },
      "fontFamily": {
        "headline-md": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "headline-xl": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "title-lg": ["Manrope", "sans-serif"],
        "headline-xl-mobile": ["Manrope", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "telemetry-metric": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-sm": ["Manrope", "sans-serif"],
        "title-md": ["Manrope", "sans-serif"]
      },
      "fontSize": {
        "headline-md": ["22px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "title-lg": ["18px", { "lineHeight": "24px", "letterSpacing": "-0.005em", "fontWeight": "600" }],
        "headline-xl-mobile": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.015em", "fontWeight": "700" }],
        "label-md": ["13px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "telemetry-metric": ["28px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.03em", "fontWeight": "500" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "title-md": ["16px", { "lineHeight": "22px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
